### ISSUE TITLE
Unaligned accesses on archs that do not support them

### ISSUE THREAD

**Issue by pornin** [status-im/nim-bearssl#12]
(This is not a security issue.)

Code in `decls.nim` explicitly defines some C macros through the C compiler invocation parameters:
https://github.com/status-im/nim-bearssl/blob/master/bearssl/decls.nim#L38
Normally, these should not be necessary (the BearSSL code itself will use defined system macros to work out the current arch and OS) but there is no harm in making some explicit definitions, except, potentially, for `BR_BE_UNALIGNED` and `BE_LE_UNALIGNED`. These macros, when defined explicitly, make BearSSL code assume that native words have a specific endianness (big-endian or little-endian, respectively), and, crucially, that unaligned accesses are gracefully handled by the hardware and the OS. "Gracefully" means that the access works with no or minimal runtime overhead.

x86, Aarch64, PowerPC (in big-endian mode), and POWER8+ (in both endianness) handle unaligned accesses gracefully (in the case of x86 and Aarch64, there is a runtime register that can be set to trap on unaligned accesses, but no OS sets it because it breaks too much code). Many old RISC architectures do not (e.g. Sparc, Alpha, Mips). Notably, "small" ARM systems (e.g. the ARM Cortex line) don't accept unaligned accesses for opcodes that access more than one word at a time. Thus, enforcing `BE_LE_UNALIGNED` on such a system may make the code crash at runtime.

I recommend not defining `BR_BE_UNALIGNED` or `BR_LE_UNALIGNED` explicitly, and let the code itself work out whether such unaligned accesses are safe or not. Moreover, use of unaligned accesses is only for performance and rarely has a noticeable impact (typically, it may be detected for bulk hashing with a fast hash function such as MD5).

**Comment by cheatfate** [comment]
Fixed in #11.
